# Importing GEO data

An alternative to mapping and computing gene counts, is to download the count matrix uploaded to the NCBI GEO database.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE143437

## Download data with:
FTP urls can be found at the GEO page.

`wget -P ../results https://ftp.ncbi.nlm.nih.gov/geo/series/GSE143nnn/GSE143437/suppl/GSE143437_DeMicheli_MuSCatlas_rawdata.txt.gz`

`wget -P ../results https://ftp.ncbi.nlm.nih.gov/geo/series/GSE143nnn/GSE143437/suppl/GSE143437%5FDeMicheli%5FMuSCatlas%5Fmetadata%2Etxt%2Egz`

In [1]:
import pandas as pd
import anndata as ad
import scanpy as sc

In [2]:
counts = pd.read_csv("../results/GSE143437_DeMicheli_MuSCatlas_rawdata.txt.gz", index_col=0, sep="\t")

In [3]:
counts.head()

,D0_A_AAACCTGAGCTATGCT,D0_A_AAACCTGAGGCCCGTT,D0_A_AAACCTGCAGCTCCGA,D0_A_AAACCTGGTGAACCTT,D0_A_AAACCTGTCAAAGACA,D0_A_AAACCTGTCGCATGGC,D0_A_AAACCTGTCGCTTAGA,D0_A_AAACGGGAGCTTTGGT,D0_A_AAACGGGGTCTAGGTT,D0_A_AAACGGGTCATGCTCC,...,D7_D_TTTGGTTGTTCTCATT,D7_D_TTTGGTTTCATCGATG,D7_D_TTTGGTTTCCAAACAC,D7_D_TTTGGTTTCGCTTAGA,D7_D_TTTGTCAAGGTGTTAA,D7_D_TTTGTCACAGTCAGCC,D7_D_TTTGTCACATACGCCG,D7_D_TTTGTCACATCGATGT,D7_D_TTTGTCAGTCCGTTAA,D7_D_TTTGTCAGTTTGTGTG
Sox17,0,1,15,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
Mrpl15,0,0,0,2,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
Lypla1,0,0,2,1,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Tcea1,0,0,1,0,0,0,1,1,0,0,...,0,2,1,0,0,1,0,0,0,1
Rgs20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
metadata = pd.read_csv("../results/GSE143437_DeMicheli_MuSCatlas_metadata.txt.gz", index_col=0, sep="\t")

In [5]:
metadata.head()

,sampleID,nUMI,nGene,percent_mito,injury,cell_annotation
D0_A_AAACCTGAGCTATGCT,D0_A,3764,1370,0.053401,Day 0,MuSCs and progenitors
D0_A_AAACCTGAGGCCCGTT,D0_A,1961,1164,0.042325,Day 0,Endothelial
D0_A_AAACCTGCAGCTCCGA,D0_A,8821,3006,0.024946,Day 0,Endothelial
D0_A_AAACCTGGTGAACCTT,D0_A,1863,711,0.029522,Day 0,Mature skeletal muscle
D0_A_AAACCTGTCAAAGACA,D0_A,1995,1157,0.037093,Day 0,Endothelial

In [6]:
assert counts.columns.all() == metadata.index.all()  # Match between counts and metadata

In [7]:
adata = ad.AnnData(X=counts.T, obs=metadata) # Transpose counts to cells x gene

In [8]:
adata

AnnData object with n_obs × n_vars = 34438 × 19208
    obs: 'sampleID', 'nUMI', 'nGene', 'percent_mito', 'injury', 'cell_annotation'